import { defineEventHandler } from "h3"

export default defineEventHandler((event) => {
  const activitiesData = {
    activities: [
      {
        id: 1,
        title: "Clasificación de vinos con el árbol de decisión",
        dataset: "Wine",
        datasetFile: "wine.tab",
        objective: "Clasificar tipos de vino según sus características químicas.",
        difficulty: "Básico",
        estimatedTime: "30 minutos",
        instructions: [
          "Abre Orange y crea un nuevo flujo de trabajo.",
          'Agrega el widget "File" y cárgale el conjunto de datos wine.tab.',
          'Conecta el widget "File" a "Tree".',
          'Haz clic en "Tree" para abrirlo y observa cómo se construye el árbol.',
          "Interpreta el primer nodo y las ramas principales del árbol.",
          'Conecta "Tree" a "Tree Viewer" y analiza visualmente la estructura del árbol.',
          'Agrega un widget "Test & Score" y conéctalo desde "File" y "Tree" para evaluar el rendimiento del modelo.',
        ],
        questions: ["¿Qué precisión tuvo el modelo?", "¿Cuál fue el atributo más importante en la raíz del árbol?"],
        widgets: ["File", "Tree", "Tree Viewer", "Test & Score"],
        category: "classification",
      },
      {
        id: 2,
        title: "Predicción del precio del vino",
        dataset: "Wine Quality",
        datasetFile: "wine-quality.tab",
        objective: "Predecir la calidad del vino usando árboles de decisión.",
        difficulty: "Intermedio",
        estimatedTime: "45 minutos",
        instructions: [
          'Usa el widget "File" para cargar wine-quality.tab.',
          'Conecta el archivo a "Select Columns" para elegir solo atributos relevantes (por ejemplo: alcohol, pH, sulphates).',
          'Conecta a "Tree" y entrena el modelo.',
          'Visualiza el árbol en "Tree Viewer".',
          'Evalúa con "Test & Score" y conecta a "Confusion Matrix".',
        ],
        questions: [
          "¿Qué valores de calidad son más fáciles de predecir?",
          "¿Qué atributos aparecen más cerca de la raíz del árbol?",
        ],
        widgets: ["File", "Select Columns", "Tree", "Tree Viewer", "Test & Score", "Confusion Matrix"],
        category: "regression",
      },
      {
        id: 3,
        title: "Diagnóstico de cáncer de mama",
        dataset: "Breast Cancer",
        datasetFile: "breast-cancer-wisconsin.tab",
        objective: "Clasificar si un tumor es benigno o maligno.",
        difficulty: "Intermedio",
        estimatedTime: "40 minutos",
        instructions: [
          'Carga el archivo breast-cancer-wisconsin.tab usando el widget "File".',
          'Elimina columnas poco útiles usando "Select Columns" (como el ID).',
          'Conecta a "Tree" y observa el árbol generado.',
          'Conecta a "Tree Viewer" y analiza el modelo.',
          'Evalúa el modelo usando "Test & Score".',
        ],
        questions: [
          "¿Qué tan confiable es el árbol para este tipo de predicción?",
          "¿Cuál es el primer atributo usado por el árbol?",
        ],
        widgets: ["File", "Select Columns", "Tree", "Tree Viewer", "Test & Score"],
        category: "medical",
      },
      {
        id: 4,
        title: "Clasificación de letras del alfabeto",
        dataset: "Letter Recognition",
        datasetFile: "letter.tab",
        objective: "Predecir letras a partir de características geométricas.",
        difficulty: "Avanzado",
        estimatedTime: "50 minutos",
        instructions: [
          'Carga la base de datos letter.tab con el widget "File".',
          'Conecta a "Tree" y entrena el modelo.',
          'Explora la complejidad del árbol con "Tree Viewer".',
          'Evalúa el modelo con "Test & Score".',
          'Usa "Confusion Matrix" para ver dónde más se equivoca.',
        ],
        questions: ["¿Qué letras son más fáciles de identificar?", "¿Cuál es la precisión general del árbol?"],
        widgets: ["File", "Tree", "Tree Viewer", "Test & Score", "Confusion Matrix"],
        category: "pattern-recognition",
      },
      {
        id: 5,
        title: "Diagnóstico de diabetes",
        dataset: "Diabetes",
        datasetFile: "diabetes.tab",
        objective: "Clasificar si una persona tiene diabetes o no, a partir de datos médicos.",
        difficulty: "Intermedio",
        estimatedTime: "35 minutos",
        instructions: [
          'Abre el conjunto diabetes.tab con el widget "File".',
          'Conecta a "Tree" y entrena el modelo.',
          'Visualiza el árbol con "Tree Viewer".',
          'Usa "Test & Score" para medir su efectividad.',
          'Agrega "Confusion Matrix" y analiza los errores del modelo.',
        ],
        questions: ["¿Qué atributo es clave para predecir la diabetes?", "¿Cuál es la tasa de falsos positivos?"],
        widgets: ["File", "Tree", "Tree Viewer", "Test & Score", "Confusion Matrix"],
        category: "medical",
      },
    ],
    categories: [
      {
        id: "classification",
        name: "Clasificación",
        description: "Actividades de clasificación de datos",
        color: "primary",
      },
      {
        id: "regression",
        name: "Regresión",
        description: "Actividades de predicción de valores",
        color: "success",
      },
      {
        id: "medical",
        name: "Diagnóstico Médico",
        description: "Aplicaciones en el área de la salud",
        color: "error",
      },
      {
        id: "pattern-recognition",
        name: "Reconocimiento de Patrones",
        description: "Identificación de patrones complejos",
        color: "warning",
      },
    ],
    difficultyLevels: [
      {
        level: "Básico",
        description: "Actividades introductorias con conceptos fundamentales",
        color: "success",
      },
      {
        level: "Intermedio",
        description: "Actividades que requieren conocimientos previos",
        color: "warning",
      },
      {
        level: "Avanzado",
        description: "Actividades complejas para usuarios experimentados",
        color: "error",
      },
    ],
    metadata: {
      course: "Técnicas Avanzadas de Programación",
      topic: "Actividades Prácticas con Árboles de Decisión",
      totalActivities: 5,
      estimatedTotalTime: "200 minutos",
      version: "1.0",
      lastUpdated: "2025-06-11",
    },
  }

  return activitiesData
})                                                                                      